# Generated by Django 5.2.4 on 2025-07-06 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('POT', 'Pothole'), ('LIT', 'Street Light'), ('GRB', 'Garbage'), ('RD', 'Road Damage'), ('OTH', 'Other')], max_length=3)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_description', models.CharField(max_length=200)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VER', 'Verified'), ('INP', 'In Progress'), ('RES', 'Resolved'), ('REJ', 'Rejected')], default='NEW', max_length=3)),
                ('upvotes', models.IntegerField(default=0)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
